import json
from django.core.management.base import BaseCommand
from apps.video_app.models import Video

class Command(BaseCommand):
    help = "Video ma'lumotlarini bazaga yuklash"

    def handle(self, *args, **options):
        videos = [
            {
                "id": 1,
                "title": "Magnit ta'sirida jismlarning harakati",
                "description": "Bolajonlarga magnit qanday jismlarni o‘ziga tortishini kichik tajriba orqali ko‘rsatamiz",
                "duration": "01:02",
                "level": "Video dars",
                "driveId": "1atWpwTHs2vNDzCjBYKnW4zfb3j_CASXf",
            },
            {
                "id": 2,
                "title": "Urug‘ unganida",
                "description": "Yerga ekilgan o‘simlik urug‘ining unib chiqishini biz bilan kuzating",
                "duration": "00:46",
                "level": "Video dars",
                "driveId": "1PfDuX5BLWLONRqDvO8LFaBj0QSohw3zr",
            },
            {
                "id": 3,
                "title": "Suv ostiga sayohat",
                "description": "Suv osti dunyosini biz bilan birgalikda kuzating",
                "duration": "00:34",
                "level": "Video dars",
                "driveId": "1nH9SVHBWBrqFgfeSDGYfrvSY4eg2vFHO",
            },
            {
                "id": 4,
                "title": "Sog‘lom hayot",
                "description": "Mikroblardan birgalikda himoyalanamiz",
                "duration": "00:30",
                "level": "Video dars",
                "driveId": "1WuOJTSP8NRjsXRaCACCaorqoPUWr1eBA",
            },
            {
                "id": 5,
                "title": "Sog‘lom tishlar",
                "description": "Tishlarimizni toza va ozoda saqlaymiz",
                "duration": "01:14",
                "level": "Video dars",
                "driveId": "1RwtHYH1cICtNzsSxEUh0DoKzPA3jMLdh",
            },
            {
                "id": 6,
                "title": "Mo‘jizakor jumrak",
                "description": "Ichimlik saqlovchi ajoyib idishni birgalikda yasaymiz",
                "duration": "01:10",
                "level": "Video dars",
                "driveId": "1z1Z3Wa9rCUMwYro1WMuxtZBOT9TQSung",
            },
            {
                "id": 7,
                "title": "Toza qo‘llar",
                "description": "Qo‘llarimizni sovun bilan yuvishning muhimligini o‘rganamiz",
                "duration": "00:43",
                "level": "Video dars",
                "driveId": "1wdF3pm7HsY5CJ-r8olfgMhSjb81NbATg",
            },
            {
                "id": 8,
                "title": "Qushlar hayoti",
                "description": "Qushlar haqida bolajonlarga ta’limiy faoliyatda foydalanamiz",
                "duration": "00:59",
                "level": "Video dars",
                "driveId": "1Og3zgFowSzHFX9o3LrEsgD57GVmbH49I",
            },
            {
                "id": 10,
                "title": "Suv charxpalagi",
                "description": "Qiziqarli suv manbai mashinasini bolalar bilan yasaymiz",
                "duration": "00:39",
                "level": "Video dars",
                "driveId": "1hzzHDYD_LgFbn3ydGwF38r6bhmA6trE0",
            },
            {
                "id": 11,
                "title": "Ijodkor matematika",
                "description": "Matematik tasavvurlarni tajriba orqali shakllantiramiz",
                "duration": "00:41",
                "level": "Video dars",
                "driveId": "1r4kxYJRXMws7Rx78G1Solpa_bRcMvS6n",
            },
            {
                "id": 12,
                "title": "Ijodkor qo‘llar",
                "description": "O‘z qo‘lingiz bilan tejamkorlik bankasini yarating",
                "duration": "01:13",
                "level": "Video dars",
                "driveId": "1JjnpUbFPCKRdzdjdXuaRbQvUzqhwrQ5W",
            },
            {
                "id": 13,
                "title": "Havoga to‘la barmoqchalar",
                "description": "San’atning eng go‘zal ko‘rinishini kashf eting va ilhom oling",
                "duration": "00:44",
                "level": "Video dars",
                "driveId": "1YX7P-JFqX0NVnzhppwtknIGjN-E0BoMb",
            },
            {
                "id": 14,
                "title": "Chuvalchanglar harakati",
                "description": "Oddiy va estetik g‘oyalar bilan o‘z asarlaringizni yarating",
                "duration": "00:58",
                "level": "Video dars",
                "driveId": "1zgOFDifydOYbv6mIwO-8gqMkkPwxr9iA",
            },
            {
                "id": 15,
                "title": "Montessori san’ati",
                "description": "Bolalarning aqlini rivojlantiruvchi faoliyatlar bilan tanishing",
                "duration": "00:58",
                "level": "Video dars",
                "driveId": "1GMV8Y5dn3I9zVRv36o4BGtw8zLNWvzwr",
            },
            {
                "id": 16,
                "title": "Stakandagi kamalak",
                "description": "O‘z stakaningizdagi ranglar olamini birgalikda yarating",
                "duration": "00:49",
                "level": "Video dars",
                "driveId": "12H4iR5IAw-89EumuOSpIqUuF9ssjlYla",
            },
            {
                "id": 17,
                "title": "Sehrli lupa",
                "description": "Lupa yordamida tasvir sirlarini kuzatamiz",
                "duration": "00:54",
                "level": "Video dars",
                "driveId": "1pCem3AWp3fHcgJtvE3P7whorBeBBTmv9",
            },
            {
                "id": 18,
                "title": "Shishadagi meduza",
                "description": "Meduzaning harakatini kuzatish bolajonlar uchun zavqli",
                "duration": "01:04",
                "level": "Video dars",
                "driveId": "1SGfG6Xg_rYQ3km6FA_DF7CcDfgC35QUo",
            },
            {
                "id": 19,
                "title": "Rangli koptokchalar",
                "description": "Bolajonlarning mayda motorikasini rivojlantiramiz",
                "duration": "01:15",
                "level": "Video dars",
                "driveId": "172FaHY4Lo9fksiTyr2vtdh6Mw6PmHXZK",
            },
            {
                "id": 20,
                "title": "Keling sog‘lom bo‘lamiz",
                "description": "Bolalar bilan birgalikda tozalikka odatlanamiz",
                "duration": "01:00",
                "level": "Video dars",
                "driveId": "1KZzt7ZPy8ToUm_fH67Ans7UoJ2-9y26z",
            },
            {
                "id": 24,
                "title": "Mo‘jizakor ranglar",
                "description": "Bolajonlar bilan birga suv va ranglar harakatini faol kuzatamiz",
                "duration": "00:47",
                "level": "Video dars",
                "driveId": "1Pw0wejRjOoKVBZUbJYdnzpcJhwY7rRlg",
            },
            {
                "id": 25,
                "title": "Havo shari",
                "description": "Bolalar bilan birgalikda ajoyib havo shari yasaymiz",
                "duration": "01:06",
                "level": "Video dars",
                "driveId": "17_4XWqn5YxzJSPgBAdaEjeU1FJJJF9Bf",
            },
            {
                "id": 26,
                "title": "Dengiz tubi",
                "description": "Dengiz jonzodlarining suvdagi faol harakatini birgalikda kuzatamiz",
                "duration": "00:40",
                "level": "Video dars",
                "driveId": "17xFIxaEIz598jtskSQVECf2T7dh1EwSN",
            },
            {
                "id": 27,
                "title": "Sirli tomchilar",
                "description": "Yog‘ va suvning o‘zaro ta’sirini qiziqarli tajriba orqali o‘rganamiz",
                "duration": "01:02",
                "level": "Video dars",
                "driveId": "1xpxBiOcbP3tq2JMdQAjl8YP1SFNk-j9P",
            },
            {
                "id": 28,
                "title": "Serhosil daraxt",
                "description": "Bu metod orqali bolalarga sonlar yozishni o‘rgatamiz",
                "duration": "01:14",
                "level": "Video dars",
                "driveId": "1nCATKmlrNafNlChflsdiPop7lRVPloQX",
            },
            {
                "id": 31,
                "title": "Aqlli sichqonchalar",
                "description": "Bolalarning matematik tasavvurlarini o‘yin orqali shakllantiring",
                "duration": "00:56",
                "level": "Video dars",
                "driveId": "1OpQFuyzq4YGeCOHBvog4vRC4LK4OaLt_",
            },
            {
                "id": 32,
                "title": "Aqliy rivojlantiruvchi chiziqlar",
                "description": "Oddiy va qiziqarli usullar yordamida bolaning fikrlashini rivojlantiring",
                "duration": "01:02",
                "level": "Video dars",
                "driveId": "1Jp_XTVpCcvKmZtmfAba5NrxbhuTMr-DD",
            },
            {
                "id": 33,
                "title": "Ranglarni saralash",
                "description": "O‘yin vaqtini o‘rganish vaqtiga aylantiring",
                "duration": "00:32",
                "level": "Video dars",
                "driveId": "1YfFMEGW8-KjIYryUqWWts8dMmaMh0nT7",
            },
            {
                "id": 34,
                "title": "Ajoyib svetafor",
                "description": "Bolalarni yo‘l harakati qoidalari bilan noodatiy tarzda tanishtiring",
                "duration": "00:36",
                "level": "Video dars",
                "driveId": "114vtFYuO9TzFHx2ylhiNSgkk5ZGeWH05",
            },
            {
                "id": 35,
                "title": "Sehrli tomchilar",
                "description": "Ijodiy loyihalar orqali bolalarning tabiiy-ilmiy dunyoqarashini boyitamiz",
                "duration": "00:54",
                "level": "Video dars",
                "driveId": "1lI6P9FTTuLW6rtpsAgQAy5LvUNBB9-ZI",
            },
            {
                "id": 36,
                "title": "Ko‘pikdan kamalak",
                "description": "Kamalakning ko‘pikdagi shakli bilan tanishing, ijodingizni rivojlantiring",
                "duration": "00:43",
                "level": "Video dars",
                "driveId": "1OcnR0wJi4kbRUj9kvNcv2oVXyu3tUU48",
            },
            {
                "id": 37,
                "title": "Suvdagi qopqoqchalar",
                "description": "Mayda motorikani tadqiqot asosida rivojlantiramiz",
                "duration": "00:46",
                "level": "Video dars",
                "driveId": "1hvX-m2mnhC7shUWPXicA2anBOv_Xmb2V",
            },
            {
                "id": 39,
                "title": "Zaryadlangan sharchalar",
                "description": "Statik elektr orqali soch va sharchalar harakatini o‘rganamiz",
                "duration": "00:39",
                "level": "Video dars",
                "driveId": "1T9F-7jMxI2hopPxo4I_mw-K4gc9zoYNw",
            },
            {
                "id": 40,
                "title": "Rangli baliqchalar",
                "description": "O‘yin va ta’lim faoliyatini uyg‘unlashtiramiz",
                "duration": "01:02",
                "level": "Video dars",
                "driveId": "1TlAOl09gdwe5HLhX7xu4Pmku5j7yejRF",
            },
            {
                "id": 41,
                "title": "Havoda harakatlanayotgan sharcha",
                "description": "Havo bosimida buyumlarning harakatini oddiy tajriba orqali kuzatamiz",
                "duration": "01:13",
                "level": "Video dars",
                "driveId": "1M1VAAdLEH1VSg3TvrCIz4ytho4hS4k2A",
            },
            {
                "id": 43,
                "title": "Bahorgi rang-barang gullar",
                "description": "Yomg‘ir ta’sirida gullarning ochilishini birgalikda kuzatamiz",
                "duration": "00:45",
                "level": "Video dars",
                "driveId": "1RMA4wpxJ4M7e5Lr67hXQD6rAxQRtI6Kj",
            },
            {
                "id": 46,
                "title": "Birgalikda gul urug‘i ekamiz",
                "description": "Gullarning unib chiqishini birgalikda kuzatamiz",
                "duration": "01:05",
                "level": "Video dars",
                "driveId": "1hNJ03XuaJaTnNEX8ATxtVLitnW3HwuBE",
            },
        ]

        created_count = 0
        for video in videos:
            video_url = f"https://drive.google.com/file/d/{video['driveId']}/view"
            obj, created = Video.objects.update_or_create(
                video_number=video["id"],
                defaults={
                    "title": video["title"],
                    "description": video["description"],
                    "video_url": video_url,
                },
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f"✅ {obj.title} qo‘shildi"))
            else:
                self.stdout.write(self.style.WARNING(f"♻️ {obj.title} yangilandi"))

        self.stdout.write(self.style.SUCCESS(f"\nJami {created_count} ta yangi video qo‘shildi ✅"))
