# Generated by Django 5.2.7 on 2025-10-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Video sarlavhasi')),
                ('video_number', models.PositiveIntegerField(verbose_name='Video raqami')),
                ('description', models.TextField(verbose_name='Video haqida')),
                ('video_url', models.URLField(verbose_name='Video linki')),
            ],
        ),
    ]
