# Generated by Django 5.2.7 on 2025-10-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_alter_video_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['video_number'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
    ]
