# Generated by Django 5.2.7 on 2025-10-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_alter_video_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('is_sent_to_telegram', models.BooleanField(default=False, verbose_name='Telegramga yuborildi')),
            ],
            options={
                'verbose_name': 'Aloqa xabari',
                'verbose_name_plural': 'Aloqa xabarlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
